version: '3'
services:
  db:
    tty: true
    image: postgres:12.5
    container_name: db
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: mytest
      POSTGRES_PASSWORD: yourPassword
      PGPASSWORD: yourPassword
      POSTGRES_DB: mytest

  dbc:
    build: ./
    container_name: dbc
    ports: 
      - "8080:80"
    # volumes: 
      # - ./dbController:/var/www/html

  web:
    image: php:7.1-apache
    container_name: web
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./webpage:/var/www/html/
      