version: '3'
services:
  db:
    tty: true
    image: mysql:5.7
    container_name: db
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
        - "4306:3306"
    environment: 
      MYSQL_DATABASE: mytest
      MYSQL_USER: mytest
      MYSQL_PASSWORD: yourPassword
      MYSQL_ROOT_PASSWORD: DGJLWwjHXDeBtn2uXKqU

  dbc:
    build: ./
    container_name: dbc
    ports: 
      - "8080:80"
    volumes: 
      - ./dbController:/var/www/html

  web:
    image: php:7.1-apache
    container_name: web
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./webpage:/var/www/html/
      